### ISSUE TITLE
Split individual functions into their own files

### ISSUE THREAD

**Issue by rmnppt** [jupabago/PropOc-package#5]
Lets split the individual functions out into files so that we have one function per file. There may be one exception to this `IdVoxel` and `IdPixel` where those could remain in one file especially if the documentation is going to be identical or very similar.

**Comment by rmnppt** [comment]
Ok I have split the functions into separate files in the latest commit.

**Comment by jupabago** [comment]
Hey Roman, 

Sorry for the late reply. I had one of those PhD nightmares when you realize that all your experiments were done improperly.
There was a change in the recipe of one of the reagents for the media I make for my experiments and I had to redo a few months of work during the last few week.
But all is good now.
Thanks for splitting up the functions.

I’ve found a couple issues with the pipeline now that I have been playing with it today, so I’ll raise them up on the Github.

Cheers, 

Juan
